### ISSUE TITLE
SyntaxError: Unexpected identifier let lircConnected

### ISSUE THREAD

**Issue by adumont** [hobbyquaker/lirc2mqtt#3]
Just installed, and 

$ lirc2mqtt --help

/usr/local/lib/node_modules/lirc2mqtt/index.js:13
let lircConnected;
    ^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Anything else I can add?

**Comment by hobbyquaker** [comment]
you need node.js 6.0 or higher to use lirc2mqtt
